city_name_map = {
    'Buirnsville': 'Burnsville',
    'Connelly': 'Connelly Springs',
    'Connelly Spring': 'Connelly Springs',
    'Connellys Springs': 'Connelly Springs',
    'Foresst City': 'Forest City',
    'Forest City, Nc 28043': 'Forest City',
    'Green Mtn': 'Green Mountain',
    'Green Mtn.': 'Green Mountain',
    'Henrrietta': 'Henrietta',
    'Mc Grady': 'McGrady',
    'Mcgrady': 'McGrady',
    'Mill Springs': 'Mill Spring',
    'Miller\'s Creek': 'Millers Creek',
    'Mooesboro': 'Mooresboro',
    'Moravianfalls': 'Moravian Falls',
    'Morgnton': 'Morganton',
    'Mroganton': 'Morganton',
    'N Wilkesboro': 'North Wilkesboro',
    'N. Wilkesboro': 'North Wilkesboro',
    'N.wilkesboro': 'North Wilkesboro',
    'North Wilesboro': 'North Wilkesboro',
    'North Wilkesbor': 'North Wilkesboro',
    'Noth Wilkesboro': 'North Wilkesboro',
    'Piney Crek': 'Piney Creek',
    'Robbinville': 'Robbinsville',
    'Ruthefordton': 'Rutherfordton',
    'Rutherford': 'Rutherfordton',
    'Wests Jefferson': 'West Jefferson',
    'Wilkeboro': 'Wilkesboro',
    'Wilkesboro, Nc 28697': 'Wilkesboro',
    'Wilkesboro28': 'Wilkesboro',
}